### ISSUE TITLE
empty / invalid bin field in package.json

### ISSUE THREAD

**Issue by DanielRuf** [shellscape/webpack-log#2]
We can probably remove the `"bin": "",` line in package.json as this throws a warning and is not really required.

> warning webpack-log@3.0.1: Invalid bin field for "webpack-log".

https://github.com/shellscape/webpack-log/blob/64b1e8e8f6c110fe984eaf6cfee204191b35d526/package.json#L10

**Comment by shellscape** [comment]
Sounds like a reasonable change to me. Please PR that and I'll publish a patch version. Short on time right now with a newborn.

**Comment by DanielRuf** [comment]
No hurry =)

And done: https://github.com/shellscape/webpack-log/pull/3

**Comment by bj00rn** [comment]
@shellscape was this ever released? Still there in 3.0.1
